name: TSK Tests on Windows

on:
  push:
    branches:
      - '**' # This will trigger the action for all branches
  pull_request:
    branches:  # Specify the branches for which pull_request events should trigger the action
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    runs-on: windows-latest

    env:
      TSK_HOME: "${{ github.workspace }}"

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v1
      - uses: microsoft/setup-msbuild@v1.1

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install nuget.commandline
          choco install ant --ignore-dependencies

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can use 'zulu' or 'adopt' as well
          java-version: '11'

      - name: Search for all jni.h files on the system
        run: |
          Get-ChildItem -Recurse -Filter jni.h -ErrorAction SilentlyContinue

      - name: Print INCLUDE environment variable
        run: echo $env:INCLUDE

      - name: Set INCLUDE environment variable (if needed)
        run: |
          # Example: Add a custom path if the jni.h directory is found but not in INCLUDE
          $jniPath = (Get-ChildItem -Recurse -Filter jni.h -ErrorAction SilentlyContinue | Select-Object -First 1).DirectoryName
          if ($jniPath) {
            echo "Found jni.h at $jniPath"
            $env:INCLUDE = "$jniPath;$env:INCLUDE"
            echo "Updated INCLUDE: $env:INCLUDE"
          }

      #- name: Restore NuGet packages
      #  run: nuget restore win32/lib

      - name: Set JDK_HOME and INCLUDE
        run: |
          echo "JDK_HOME=$(Get-Command java).Path.Replace('\bin\java.exe', '')" >> $GITHUB_ENV
          echo "INCLUDE=${{ env.JDK_HOME }}/include;${{ env.JDK_HOME }}/include/win32" >> $GITHUB_ENV

      - name: Build TSK
        run: |
          python win32\updateAndBuildAll.py -m

      - name: Build Java
        run: |
          ant -version
          cd bindings\java
          ant -q dist
          cd ..\..
          cd case-uco\java
          ant -q
          cd ..\..
